kind: pipeline
name: default

steps:
- name: build
  image: php:8.2-fpm-alpine
  commands:
    # Update packages
  - php -v
  # Install php extensions
  - docker-php-ext-install cli dev fpm pgsql sqlite3 gd imagick curl imap mysql mbstring xml zip bcmath soap intl readline ldap msgpack igbinary redis swoole memcached pcov xdebug common
