kind: pipeline
name: default

services:
- name: database
  image: mariadb:10
  environment:
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    MYSQL_DATABASE: testing

steps:
  - name: frontend
    image: node:18
    commands:
    - npm install
    - npm run prod

  - name: library
    image: composer
    commands:
    - composer install --ignore-platform-req=ext-*

  - name: test_database
    image: mariadb:10
    commands:
    - sleep 30
    - mysql -u root -h database --execute="SELECT VERSION();"
    depends_on:
    - database

  - name: build_test_app
    image: ubuntu:24.04
    commands:
    - ln -snf /usr/share/zoneinfo/UTC /etc/localtime && echo UTC > /etc/timezone
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -q gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev python3 dnsutils librsvg2-bin
    - curl -sS 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x14aa40ec0831756756d7f66c4f4ea0aae5267a6c' | gpg --dearmor | tee /etc/apt/keyrings/ppa_ondrej_php.gpg > /dev/null
    - echo "deb [signed-by=/etc/apt/keyrings/ppa_ondrej_php.gpg] https://ppa.launchpadcontent.net/ondrej/php/ubuntu noble main" > /etc/apt/sources.list.d/ppa_ondrej_php.list
    - apt-get update
    - DEBIAN_FRONTEND=noninteractive apt-get install -y -q php8.3-cli php8.3-dev php8.3-fpm php8.3-pgsql php8.3-sqlite3 php8.3-gd php8.3-imagick php8.3-curl php8.3-imap php8.3-mysql php8.3-mbstring php8.3-xml php8.3-zip php8.3-bcmath php8.3-soap php8.3-intl php8.3-readline php8.3-ldap php8.3-msgpack php8.3-igbinary php8.3-redis php8.3-swoole php8.3-memcached php8.3-pcov php8.3-xdebug php8.3-common
    - ls
    - cp .env.testing .env
    - cp config/settings.php.example config/settings.php
    - php artisan config:cache
    - php artisan migrate
    - php artisan db:seed
    - mkdir storage/images && mkdir storage/avatar && mkdir storage/sound && mkdir storage/files
    - php artisan storage:link
    - nohup php artisan serve &
    - php artisan test --parallel --recreate-databases
    depends_on:
    - frontend
    - library
    - test_database
