kind: pipeline
name: default

steps:
  - name: test
    image: php:8.2-fpm
    commands:
    - apt-get update
    - apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev dnsutils librsvg2-bin
    - apt-get install -y apt-transport-https lsb-release software-properties-common
    - add-apt-repository ppa:ondrej/php
    - apt-get update
    - apt-get install -y php8.2-cli php8.2-{dev pgsql sqlite3 gd imagick curl imap mysql mbstring xml zip bcmath soap intl readline ldap msgpack igbinary redis swoole memcached pcov xdebug common}
    - docker-php-ext-enable cli dev pgsql sqlite3 gd imagick curl imap mysql mbstring xml zip bcmath soap intl readline ldap msgpack igbinary redis swoole memcached pcov xdebug common
    #- docker-php-ext-enable &&
    #- cp .env.example .env
    - #php artisan key:generate
