kind: pipeline
name: default

steps:
  - name: test
    image: php:8.2-fpm
    commands:
    - apt-get update
    - apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev dnsutils librsvg2-bin
    - apt-get install -y apt-transport-https lsb-release wget
    - wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    - sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list'
    - apt-get update
    - apt-get install -y php8.2-cli php8.2-{dev pgsql sqlite3 gd imagick curl imap mysql mbstring xml zip bcmath soap intl readline ldap msgpack igbinary redis swoole memcached pcov xdebug common}
    - docker-php-ext-enable cli dev pgsql sqlite3 gd imagick curl imap mysql mbstring xml zip bcmath soap intl readline ldap msgpack igbinary redis swoole memcached pcov xdebug common
    #- docker-php-ext-enable &&
    #- cp .env.example .env
    - #php artisan key:generate
