kind: pipeline
name: default

steps:
  - name: test
    image: php:8.2-fpm
    commands:
    - apt-get update
    - apt-get install -y gnupg gosu curl ca-certificates zip unzip git supervisor sqlite3 libcap2-bin libpng-dev dnsutils librsvg2-bin
    - docker-php-ext-configure pdo_mysql
    - docker-php-ext-install pdo_mysql
    - cp .env.example .env
    - php artisan key:generate
