services:
    app:
        build:
            context: ./build/php
            dockerfile: Dockerfile
        image: chel-region-helpdesk/app
        container_name: app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - 9000
        volumes:
            - './:/var/www/html'
        networks:
            - laravel
        depends_on:
            - mariadb
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    nginx:
        image: nginx:alpine
        container_name: nginx
        ports:
            - 80:80
        volumes:
           - './:/var/www/html'
           - ./build/ngnix:/etc/nginx/conf.d/
        networks:
        - laravel
        depends_on:
            - app
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    mariadb:
        image: 'mariadb:10'
        container_name: mariadb
        ports:
            - '3306:3306'
        volumes:
           - './output/mariadb:/var/lib/mysql'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - laravel
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    redis:
        image: redis:alpine
        container_name: redis
        ports:
            - '6379:6379'
        volumes:
           - './output/redis:/data'
        networks:
            - laravel
        depends_on:
            - nginx
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    phpmyadmin:
        image: 'phpmyadmin:latest'
        container_name: phpmyadmin
        ports:
          - 8081:80
        environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        links:
          - "mariadb:db"
        depends_on:
          - mariadb
        networks:
          - laravel
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    soketi:
        build:
            context: ./build/php
            dockerfile: Dockerfile
        image: chel-region-helpdesk/app
        container_name: soketi
        ports:
            - '6001:6001'
        expose:
            - "6001"
        tty: true
        volumes:
           - './:/var/www/html'
        command: ["su", "root", "-c", "soketi start --config=/var/www/html/soketi.json"]
        networks:
            - laravel
        depends_on:
            - nginx
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    shedule:
        build:
            context: ./build/php
            dockerfile: Dockerfile
        image: chel-region-helpdesk/app
        volumes:
           - './:/var/www/html'
        container_name: shedule
        command: ["su", "root", "-c", "php artisan schedule:work"]
        networks:
            - laravel
        depends_on:
            - app
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
    queue:
        build:
            context: ./build/php
            dockerfile: Dockerfile
        image: chel-region-helpdesk/app
        volumes:
           - './:/var/www/html'
        container_name: queue
        command: ["su", "root", "-c", "php artisan queue:work"]
        networks:
            - laravel
        depends_on:
            - shedule
            - app
        logging:
            options:
                max-size: "10m"
                max-file: "3"
        restart: unless-stopped
networks:
    laravel:
        driver: bridge
